services:
  - type: static
    name: react-portfolio
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production
